on: [push, pull_request, workflow_dispatch]

jobs:
  matrix:
    runs-on: ubuntu-22.04
    name: Fetch Build Keyboards
    outputs:
      build_matrix: ${{ env.build_matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yaml2json
        run: python3 -m pip install remarshal

      - name: Fetch Build Matrix
        run: |
          echo "build_matrix=$(yaml2json '${{ inputs.build_matrix_path }}' | jq -c .)" >> $GITHUB_ENV
          yaml2json "${{ inputs.build_matrix_path }}" | jq
          echo "Build matrix JSON: ${{ env.build_matrix }}"

      - name: Validate JSON
        run: |
          echo "${{ env.build_matrix }}" | jq . || exit 1


      # Other steps remain the same...
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
 
